name: "spdlog"
description: "Very fast, header only, C++ logging library"
version: "1.6.1"
build:
  packages:
    spdlog:
      cflags: ['-DSPDLOG_COMPILED_LIB']
  libraries: ['pthread']
test:
  bits:
    cest: '1.0'
